### ISSUE TITLE
What is it called "DDT"?

### ISSUE THREAD

**Issue by Bilge** [okdana/ddt#1]

**Comment by okdana** [comment]
It was meant to be sort of a play on words. The tool it was based on was called `roundup`, apparently after the [herbicide](https://en.wikipedia.org/wiki/Glyphosate), so i named my implementation `ddt` after the [insecticide](https://en.wikipedia.org/wiki/DDT). ¯\_(ツ)_/¯

**Comment by Bilge** [comment]
What a wacky and crazy story. I enjoyed it very much :+1:
