### ISSUE TITLE
Deprecated in favour of what?

### ISSUE THREAD

**Issue by Bilge** [okdana/ddt#10]
Couldn't help but notice the repo is marked as _deprecated_, but what do you recommend using instead?

**Comment by okdana** [comment]
I don't really have any specific recommendations.

When it comes to testing command-line tools (not shell functions), it's pretty trivial to implement your own test harness, so a lot of big projects like Git and systemd seem to just do that. TAP-style tools seem common also.

For testing actual shell functions and plug-ins, i'm not aware of any common conventions. zsh is the only other project i have experience with that does that, and it has its own custom (and somewhat complicated) test harness.

**Comment by Bilge** [comment]
Thanks for your suggestions and insights.

I still think this is an important tool, without equal. There aren't a lot of people in the World who understand Bash, even if they think they do, so it's unlikely an alternative will emerge any time soon.
