### ISSUE TITLE
declare: -g: invalid option

### ISSUE THREAD

**Issue by Bilge** [okdana/ddt#4]
Not only was it my [previous recommendation](https://github.com/okdana/ddt/pull/2#discussion_r54945687) to remove the `-g` option because it is redundant but it is also invalid in some versions of Bash. 

```sh
$ bash --version
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
$ declare -g
-bash: declare: -g: invalid option
```

This manifests itself as the following error when running `ddt`.

```sh
$ ddt
/usr/local/bin/ddt: line 31: declare: -g: invalid option
declare: usage: declare [-aAfFilrtux] [-p] [name[=value] ...]
sed: can't find label for jump to `mp.rWfDxODOQi'
```

**Comment by okdana** [comment]
That version of bash is 6+ years old, that's cray. But i do say that `ddt` is compatible with bash 4.0+, so i'd be a liar if i didn't fix it ¯\\\_(ツ)\_/¯

I've posted [v0.1.1](https://github.com/okdana/ddt/releases/tag/v0.1.1), let me know if you find any other problems with your Flintstones computer :/\
