### ISSUE TITLE
plan:before_plan should output something when it fails

### ISSUE THREAD

**Issue by Bilge** [okdana/ddt#5]
Currently `plan:before_plan` gives no indication if any of the setup steps fail. This is a usability problem since we can have the reasonable expectation that if any command fails it indicates an error in the setup steps. Since there is no output whatsoever, not only do we not know a failure has occurred but it's also very difficult to debug.

**Comment by okdana** [comment]
What would you suggest?

Do you just want to see the output? Or do you want it run with `set -e` like the tests?

And should that also apply to `plan:before_test`? And the after-test/plan ones too?

**Comment by Bilge** [comment]
I think it should look like when a test case fails ( `set -e` style), with the backtrace-looking output.

Yes it should also apply to the before/after other methods, too.

**Comment by okdana** [comment]
Should an error in the before-functions abort the plan/test?

**Comment by okdana** [comment]
Actually, looking at it now, there are some difficulties with making these functions execute/fail like the test ones do. Their purpose was to perform set-up for the tests, like creating files or setting variables. If these functions run in a sub-shell like the tests do, they can't affect the tests' execution environment. The `ddt.ddtt` plan in the repo demonstrates this; the change causes it to fail:

```
ddt(1) self-test
  ...
  runs plan:before_plan ................................................. [FAIL]
    + [[ -n '' ]]
  runs plan:before_test ................................................. [FAIL]
    + [[ -n '' ]]

--- ddt test results ---
8 test(s) performed: 6 passed, 2 failed, 75% success
```

Exposing the functions' output would be a very trivial change, but i guess changing their behaviour otherwise would require some thought. Off the top of my head i can't think of a reliable way to make them work like the tests without sacrificing this functionality. I guess if you wanted we could define some new functions that carry different implications, but idk.

**Comment by Bilge** [comment]
Yes, errors in _before_ functions should indicate a state where the tests wouldn't be able to run anyway, so it should abort there.

Why are you trying to run them in a subshell?

**Comment by okdana** [comment]
`set -e` causes the current (sub-)shell to immediately halt when a command returns non-`0`, so if the function wasn't executed in a sub-shell, it'd abort the entire plan and you'd get no explanation for why.

One alternative might be to not use `set -e`, but only check the *final* return status. Something like:

```
{
  set -x # Trace only, no -e
  plan:before_test
  ret=$? # Capture the *final* status
  set +x
} > "${ddt[temp]}/plan:before_test" 2>&1

(( ret )) && {
  ddt:signal_result ... # Whatever, signal failure somehow
  continue # Don't run test
}
```

Then your functions would look like:

```
plan:before_test() {
  false # This won't fail the function
  ... # Whatever other code
  return 1 # This will fail the function
}
```

**Comment by Bilge** [comment]
We really need `set -e` because it's no good to only check the exit code. We need to know if any pipeline fails.

**Comment by okdana** [comment]
I don't think it uses `pipefail`, so unless you're setting that yourself it's not currently doing that for you. I can add that though.

In any case, if you need the `set -e` behaviour there are two options i can think of:

1. Just change the before/after-functions to run in a sub-shell, entirely eliminating the ability to modify the plan's execution environment between tests

2. Split the before/after-functions into one set with the `set -e` behaviour and one set without

To be completely honest, i haven't really been using ddt over the last 2 or 3 years, and i don't think anyone else does besides you. And i'm not happy with the design anyway, so if i decided i was going to pick it up again i'd probably make an incompatible ddt2 or something. Sooo... if you don't personally care about the functionality loss, we can do option 1

**Comment by Bilge** [comment]
I don't have any use case for option 1. What exactly are you able to modify? Environment variables? Anyway, as mentioned, I don't currently need it. I'm just trying to figure out if that could ever be useful.

**Comment by okdana** [comment]
You can currently modify anything about the environment that the tests execute in — variables, shell options, &c. In xUnit-style test suites the equivalent feature might be used to re-initialise a shared object to a known good state. In the shell you'd more likely use it for deleting temp files (which is fine to do in a sub-shell) or resetting a persistent counter or array (which is not).

**Comment by Bilge** [comment]
If you need a shared object you create it in your test script, you don't need a superglobal for that.

**Comment by okdana** [comment]
Not sure what you mean.

[This](https://phpunit.readthedocs.io/en/8.0/fixtures.html#fixtures-examples-stacktest-php) is an example of how `setUp()` (the equivalent to `plan:before_test`) can be used in PHPUnit.

That kind of thing would probably not be too common when using ddt to test external scripts, but you'd run into it more often if you used it to test actual shell functions (which is partially what i created it for). Even when testing scripts, though, you might want to for example `cd` to a temp directory before each test. You wouldn't be able to do that in a sub-shell; the best you could do would be to create your own pre-test function and copy and paste it at the top of every single test function.

If that's an acceptable limitation, we can sub-shell the functions

(FWIW, [roundup](https://github.com/bmizerany/roundup/blob/master/roundup.sh#L241), ddt's inspiration, aborts if there's any non-`0` return in `before` or `after` (`set -e`), but it also suppresses the output, which honestly seems even worse)

**Comment by Bilge** [comment]
I actually do `cd` in the *before_test*. We could always special-case the working directory but that's probably not a good idea.

**Comment by Bilge** [comment]
Actually, it seems to me the only thing you need to do is make sure all these test methods run in the _same_ subshell. As long as they do, they can continue to "talk" to each other with side effects as desired.

**Comment by okdana** [comment]
Oh, that is a good idea actually. The only issue is that there won't be any way to communicate to the 'summariser' that it's the before/after function that failed rather than the test itself; i can make it more obvious what's happening by just not stripping the first line out of the trace.

And then you still want the before-/after-plan functions to bail too, right?

**Comment by Bilge** [comment]
Yes, if it fails it should not continue. I don't think it makes sense to continue if something is broken.

**Comment by okdana** [comment]
Is this acceptable?

**Failing before-plan function**

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:before_plan() { false; }
test:is_ok() { true; }

test
  before/after-plan function executes without error ..................... [FAIL]

--- ddt test results ---
0 test(s) performed: 0 passed, 0 failed, 0% success; 1 error(s)
```

**Failing after-plan function**

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:after_plan() { false; }
test:is_ok() { true; }

test
  is ok ................................................................. [PASS]
  before/after-plan function executes without error ..................... [FAIL]

--- ddt test results ---
1 test(s) performed: 1 passed, 0 failed, 100% success; 1 error(s)
```

**Failing before-test function**

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:before_test() { false; }
test:is_ok() { true; }

test
  is ok ................................................................. [FAIL]
    + plan:before_test
    + false

--- ddt test results ---
1 test(s) performed: 0 passed, 1 failed, 0% success
```

**Failing after-test function**

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:after_test() { false; }
test:is_ok() { true; }

test
  is ok ................................................................. [FAIL]
    + plan:before_test
    + :
    + test:is_ok
    + true
    + plan:after_test
    + false

--- ddt test results ---
1 test(s) performed: 0 passed, 1 failed, 0% success
```

**Comment by Bilge** [comment]
Why is there no trace for before/after plan?

**Comment by okdana** [comment]
Needs some FD juggling to make it work right. I think this does it:

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:before_plan() { false; }
test:is_ok() { true; }

test
  ddt: before/after-plan function executes without error ................ [FAIL]
    + plan:before_plan
    + false

--- ddt test results ---
0 test(s) performed: 0 passed, 0 failed, 0% success; 1 error(s)
```

```
% cat test.ddtt && echo && ./ddt test.ddtt
plan:after_plan() { false; }
test:is_ok() { true; }

test
  is ok ................................................................. [PASS]
  ddt: before/after-plan function executes without error ................ [FAIL]
    + plan:after_plan
    + false

--- ddt test results ---
1 test(s) performed: 1 passed, 0 failed, 100% success; 1 error(s)
```

**Comment by Bilge** [comment]
Great :clap:

**Comment by Bilge** [comment]
I think, in light of these changes, we should bump the version number (`ddt -V`).

**Comment by okdana** [comment]
That seems reasonable, done
