### ISSUE TITLE
When a test fails, plan:after_test is not run

### ISSUE THREAD

**Issue by Bilge** [okdana/ddt#7]
Since ddt continues running tests after a failure, it is important that `plan:after_test` also runs after the failures, to ensure state is clean for the next test run. Otherwise, one test failure can cause subsequent tests to fail when they otherwise would not.

**Comment by okdana** [comment]
Yeah, that's a side-effect of running together with `set -e` in the same sub-shell. What i can do is try putting the test itself in *another* sub-shell and then juggling the return status manually. This will make the test function unable to affect the environment of the after-test function; idk if that's a concern.

**Comment by okdana** [comment]
Can you try the branch `dana/7` and see if it works the way you want? I think the only issue should be the one i mentioned, but i didn't test super extensively

**Comment by Bilge** [comment]
It seems to "work", in the sense that it definitely does execute `plan:after_test`, but there is a problem with the debug output. The output from the test seems to be merged with the output from `plan:after_test`, even if `plan:after_test` succeeded without error. Moreover, it used to highlight the test line that caused an error, but now it just highlights whatever the last line executed by `plan:after_test` was.

So yes, it works, but the stack trace is scuffed.

**Comment by okdana** [comment]
Yeah. The trace output is going to be a little inconsistent when using this method because it all gets sent to the same place at once. I'm sure there are ways around it, but the ones i can think of require more re-architecting than i'm willing to do right now.

I think i can fix the immediate problem though. I've updated that branch — i think you should find now that if the test function fails the trace stops there. Is that OK?

**Comment by Bilge** [comment]
Looks good to me. The only oddity is you won't see any `plan:after_test` failures unless the test itself passed (even though `plan:after_test` still runs regardless of whether the test passed).

**Comment by okdana** [comment]
Yeah it'll have to be like that for now i guess
